// typesense-next-search-bar/components/BookList.tsx
import { useHits } from "react-instantsearch";
import type { Book } from "../types/Book";
import { BookCard } from "./BookCard";
import styles from "./BookList.module.css";

export const BookList = () => {
  const { items } = useHits<Book>();

  if (!items || items.length === 0) {
    return (
      <div className={styles.emptyState}>
        {items
          ? "No books found. Try a different search term."
          : "Start typing to search for books."}
      </div>
    );
  }

  return (
    <div className={styles.bookList}>
      {items.map((item) => (
        <BookCard key={item.objectID} book={item as unknown as Book} />
      ))}
    </div>
  );
};

// typesense-solid-js-search/src/components/BookList.tsx
import { For, Show } from "solid-js";
import { BookCard } from "./BookCard";
import styles from "./BookList.module.css";
import type { Book } from "../types/Book";

interface BookListProps {
  books: Book[];
  loading: boolean;
}

export function BookList(props: BookListProps) {
  return (
    <div class={styles.bookList}>
      <Show when={props.loading}>
        <div class={styles.loadingContainer}>
          <div class={styles.spinner}></div>
          <p>Searching...</p>
        </div>
      </Show>

      <Show when={!props.loading && props.books.length === 0}>
        <div class={styles.noResults}>
          <h3>No books found</h3>
          <p>Try adjusting your search or try different keywords.</p>
        </div>
      </Show>

      <Show when={!props.loading && props.books.length > 0}>
        <div class={styles.bookGrid}>
          <For each={props.books}>{(book) => <BookCard book={book} />}</For>
        </div>
      </Show>
    </div>
  );
}
