// typesense-next-search-bar/components/BookCard.tsx
import type { Book } from "../types/Book";
import styles from "./BookCard.module.css";

interface BookCardProps {
  book: Book;
}

export const BookCard = ({ book }: BookCardProps) => {
  const {
    title,
    authors,
    publication_year,
    image_url,
    average_rating,
    ratings_count,
  } = book;

  return (
    <div className={styles.bookCard}>
      <div className={styles.bookImageContainer}>
        {image_url ? (
          <img
            src={image_url}
            alt={title}
            className={styles.bookImage}
            onError={(e) => {
              (e.target as HTMLImageElement).src = "/book-placeholder.png";
            }}
          />
        ) : (
          <div className={styles.noImage}>No Image</div>
        )}
      </div>
      <div className={styles.bookInfo}>
        <h3 className={styles.bookTitle}>{title}</h3>
        <p className={styles.bookAuthor}>By: {authors?.join(", ")}</p>
        {publication_year && (
          <p className={styles.bookYear}>Published: {publication_year}</p>
        )}
        <div className={styles.ratingContainer}>
          <div className={styles.starRating}>
            {"★".repeat(Math.round(average_rating || 0))}
          </div>
          <span className={styles.ratingText}>
            {average_rating?.toFixed(1)} ({ratings_count?.toLocaleString()}{" "}
            ratings)
          </span>
        </div>
      </div>
    </div>
  );
};

// typesense-angular-search-bar/src/app/components/book-card/book-card.component.ts
import { Component, Input } from '@angular/core';
import { Book } from '../../types/book';

@Component({
  selector: 'app-book-card',
  standalone: true,
  templateUrl: './book-card.component.html',
  styleUrl: './book-card.component.css',
})
export class BookCardComponent {
  @Input({ required: true }) book!: Book;

  get stars(): string {
    return '\u2605'.repeat(Math.round(this.book.average_rating || 0));
  }

  get formattedRating(): string {
    return (this.book.average_rating || 0).toFixed(1);
  }

  get formattedRatingsCount(): string {
    return (this.book.ratings_count || 0).toLocaleString();
  }

  get authorList(): string {
    return this.book.authors?.join(', ') ?? '';
  }

  onImageError(event: Event): void {
    (event.target as HTMLImageElement).style.display = 'none';
  }
}

<div class="book-card">
  <div class="book-image-container">
    @if (book.image_url) {
      <img
        [src]="book.image_url"
        [alt]="book.title"
        class="book-image"
        (error)="onImageError($event)"
      />
    } @else {
      <div class="no-image">No Image</div>
    }
  </div>

  <div class="book-info">
    <h3 class="book-title">{{ book.title }}</h3>
    <p class="book-author">By: {{ authorList }}</p>

    @if (book.publication_year) {
      <p class="book-year">Published: {{ book.publication_year }}</p>
    }

    <div class="rating-container">
      <div class="star-rating">{{ stars }}</div>
      <span class="rating-text">
        {{ formattedRating }} ({{ formattedRatingsCount }} ratings)
      </span>
    </div>
  </div>
</div>
