// typesense-nuxt-search-bar/components/BookList.vue
<script setup lang="ts">
import { AisHits } from "vue-instantsearch/vue3/es";
import type { Book } from "../types/Book";
import BookCard from "./BookCard.vue";
</script>

<template>
  <ais-hits>
    <template #default="{ items }">
      <div v-if="!items || items.length === 0" class="empty-state">
        {{
          items
            ? "No books found. Try a different search term."
            : "Start typing to search for books."
        }}
      </div>
      <div v-else class="book-list">
        <BookCard
          v-for="item in items"
          :key="item.objectID"
          :book="item as unknown as Book"
        />
      </div>
    </template>
  </ais-hits>
</template>

<style scoped>
.book-list {
  display: grid;
  grid-template-columns: 1fr;
  gap: 1.5rem;
  padding: 1.5rem 0;
}

@media (min-width: 768px) {
  .book-list {
    grid-template-columns: repeat(2, 1fr);
  }
}

@media (min-width: 1024px) {
  .book-list {
    grid-template-columns: repeat(3, 1fr);
  }
}

.empty-state {
  text-align: center;
  padding: 3rem 0;
  color: #6b7280;
}
</style>

// typesense-sveltekit-search-app/src/lib/components/BookList.svelte
<script lang="ts">
  import type { SearchService } from '../searchService.svelte';
  import BookCard from './BookCard.svelte';

  interface Props {
    searchService: SearchService;
  }

  let { searchService }: Props = $props();
</script>

{#if !searchService.hasSearched}
  <div class="emptyState">
    Loading search client...
  </div>
{:else}
  {#if searchService.hits.length === 0}
    <div class="emptyState">
      {#if searchService.query}
        No books found. Try a different search term.
      {:else}
        Start typing to search for books.
      {/if}
    </div>
  {:else}
    <div class="bookList">
      {#each searchService.hits as book (book.objectID || book.id)}
        <BookCard {book} />
      {/each}
    </div>
  {/if}
{/if}

<style>
.bookList {
  display: grid;
  grid-template-columns: 1fr;
  gap: 1.5rem;
  padding: 1.5rem 0;
}

@media (min-width: 768px) {
  .bookList {
    grid-template-columns: repeat(2, 1fr);
  }
}

@media (min-width: 1024px) {
  .bookList {
    grid-template-columns: repeat(3, 1fr);
  }
}

.emptyState {
  text-align: center;
  padding: 3rem 0;
  color: #6b7280;
}
</style>
