// typesense-next-search-bar/components/SearchBar.tsx
import { SearchBox } from "react-instantsearch";
import styles from "./Searchbar.module.css";

export const SearchBar = () => {
  return (
    <div className={styles.searchContainer}>
      <SearchBox
        placeholder="Search for books by title or author..."
        classNames={{
          form: styles.searchForm,
          input: styles.searchInput,
          submit: styles.searchButton,
          reset: styles.resetButton,
        }}
        submitIconComponent={() => (
          <svg
            className={styles.searchIcon}
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
            />
          </svg>
        )}
        resetIconComponent={() => (
          <svg
            className={styles.closeIcon}
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M6 18L18 6M6 6l12 12"
            />
          </svg>
        )}
        loadingIconComponent={() => <div className={styles.loadingSpinner} />}
      />
    </div>
  );
};

// typesense-angular-search-bar/src/app/components/search-bar/search-bar.component.ts
import { Component, NgZone, OnInit, OnDestroy } from '@angular/core';
import connectSearchBox from 'instantsearch.js/es/connectors/search-box/connectSearchBox';
import { SearchService } from '../../services/search.service';

@Component({
  selector: 'app-search-bar',
  standalone: true,
  templateUrl: './search-bar.component.html',
  styleUrl: './search-bar.component.css',
})
export class SearchBarComponent implements OnInit, OnDestroy {
  query = '';
  private refineFn: (value: string) => void = () => {};
  private widget: ReturnType<ReturnType<typeof connectSearchBox>> | null = null;

  constructor(
    private searchService: SearchService,
    private ngZone: NgZone,
  ) {}

  ngOnInit(): void {
    const searchBoxConnector = connectSearchBox((renderOptions) => {
      this.ngZone.run(() => {
        this.query = renderOptions.query;
        this.refineFn = renderOptions.refine;
      });
    });
    this.widget = searchBoxConnector({});
    this.searchService.searchInstance.addWidgets([this.widget]);
  }

  onSearch(event: Event): void {
    const value = (event.target as HTMLInputElement).value;
    this.refineFn(value);
  }

  onReset(): void {
    this.refineFn('');
  }

  ngOnDestroy(): void {
    if (this.widget) {
      this.searchService.searchInstance.removeWidgets([this.widget]);
    }
  }
}

<div class="search-container">
  <div class="search-form">
    <button class="search-button" type="button">
      <svg
        class="search-icon"
        fill="none"
        stroke="currentColor"
        viewBox="0 0 24 24"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
        ></path>
      </svg>
    </button>

    <input
      type="search"
      class="search-input"
      [value]="query"
      (input)="onSearch($event)"
      placeholder="Search for books by title or author..."
    />

    @if (query) {
      <button class="reset-button" type="button" (click)="onReset()">
        <svg
          class="close-icon"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M6 18L18 6M6 6l12 12"
          ></path>
        </svg>
      </button>
    }
  </div>
</div>
